app-name: roster
initials: ojer
language: gradle

github-app-repo-uri: "git@github.com:thekkudan/roster.git"

github-pipelines-repo-uri: "git@github.com:thekkudan/training-pipelines.git"

cf-dev-api: api.run.pivotal.io
cf-dev-org: rscale-training-3
cf-dev-space: rejo
cf-dev-hostname: roster-rthekkudan
cf-dev-domain: cfapps.io
cf-dev-manifest: roster.yml

