---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli

inputs:
- name: app-source
- name: version
- name: pipelines
- name: artifact

run:
  path: pipelines/cf/tasks/blue-green-deploy.sh
